### ISSUE TITLE
The behavior of anaconda-mode-show-doc is confusing

### ISSUE THREAD

**Issue by SleepyBag** [pythonic-emacs/anaconda-mode#369]
When I call anaconda-mode-show-doc, it always tries to reuse a currently opened window. This behavior is weird for me because I thought the document should be shown in a newly-opened window. 
I thought there should be someone having the same problem as me but surprisingly not. So I check the source code of anaconda-mode and find out that anaconda-mode uses pop-to-buffer to eventually show the document. I tried to call pop-to-buffer myself and got the same behavior - it always chooses a opened window and put the buffer into it.
So I'd like to know if it is meant to behave this way. if so, would it be better to show documentation always in a new window? If not, is there any idea about fixing this problem? I am using spacemacs and not sure if this is an issue about spacemacs.

**Comment by dakra** [comment]
I changed the function to always open the documentation in the "other window".
I hope this doesn't break anyones workflow. If so, we could easily make this a defcustom.
But since all other help buffers (including Emacs own) always open in the other window and the default `pop-to-buffer` sometimes opens here and sometimes there I think it makes sense the way you described it.
